---
- name: Install and configure gitlab
  hosts: "{{ variable_host }}"  
  become: true

  vars_files:
    - variables.yml


  tasks:
    - name: Run runner script #https://docs.gitlab.com/runner/install/linux-repository.html
      command: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | sudo bash
      register: configure_result
    - debug: var=configure_result

    - name: Install packages
      yum:
        name:
          - gitlab-runner
        state: present
      # environment:
      #   EXTERNAL_URL: "{{ pipeline_hostname }}"


