---
- name: Prepare centos for gitlab install
  hosts: "{{ variable_host }}"
  # vars_files:
  #   - vars/iim.yml
  #   - vars/ihs.yml
  # hosts: all
  become: true


  tasks:
    - name: Add epel-release repo
      yum:
        name: epel-release
        state: present

    - name: Install package with multiple repos enabled
      yum:
        name: sos
        enablerepo: "epel"

    - name: Install packages
      yum:
        name: 
          - curl
          - policycoreutils-python
          - postfix
        state: present

    - name: Start postfix
      service:
        name: postfix
        state: started

    - name: Download gitlab repo script
      get_url:
        url: https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.rpm.sh
        dest: /tmp/gitlab-script.sh
        mode: '0755'

    - name: Run above script
      command: /tmp/gitlab-script.sh

    
    