---
- name: Install mongodb
  hosts: "{{ variable_host }}"
  become: true
  vars:
      mongodb_version: "3.6"
# names and passwords for administrative users
      mongodb_user_admin_name: siteUserAdmin
      mongodb_user_admin_password: passw0rd

      mongodb_root_admin_name: siteRootAdmin
      mongodb_root_admin_password: passw0rd
  tasks:
 #   - name: Install mongodb galaxy role

  roles:
    - undergreen.mongodb
