---
- name: Install and configure software on pipeline instance
  hosts: all
  become: true

  # vars:
  #   helloworld: Meow!

  tasks:


  - name: Add epel-release repo
    yum:
      name: epel-release
      state: present

  - name: copy repo file
    template:
      src: templates/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: Install packages
    yum:
      name: 
        - unzip
        - centos-release-scl
        - ansible
        - golang-go
        - kubectl
      state: present

  - name: Install python after scl above
    yum:
      name: 
        - rh-python36
      state: present

  # - name: Enable scl to make python 3.6 default
  #   command: scl enable rh-python36 bash

  - name: Download packer
    unarchive:
      src: https://releases.hashicorp.com/packer/1.4.1/packer_1.4.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755

  - name: Download terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755

  - name: Install helm
    unarchive: 
      src: https://get.helm.sh/helm-v2.14.1-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: copy rbac for helm eks
  #https://eksworkshop.com/helm/deploy/
    template:
      src: templates/rbac.yaml
      dest: /tmp/rbac.yaml
