- hosts: 127.0.0.1

  vars:
          #foo: ""          # foo is defined and foo == '' and foo != None
    bar:             # bar is defined and bar != '' and bar == None

  tasks:

  - debug:
      msg: "foo is defined and foo == '' and foo != None"
    when: foo is defined and foo == '' and foo != None

  - name: Install mongodb galaxy role
    command: ansible-galaxy install girder.mongodb
      register: configure_result
    - debug: var=configure_result
